old_sound_rabbit_mq:
    connections:
        default:
            host: "%rabbitmq.host%"
            port: "%rabbitmq.port%"
            user: "%rabbitmq.username%"
            password: "%rabbitmq.password%"
            vhost: /
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3
